formkiq/formkiq-console

- src/app/plugins/document-explorer/components/searchbar/searchbar.component.html
- src/app/plugins/document-explorer/components/searchbar/searchbar.component.ts
> made date picker text field readonly

- src/app/plugins/document-explorer/pages/add/add.component.scss
- src/app/plugins/document-explorer/pages/add/add.component.ts
updated dropzone text with "drag or click" and max num files
> stretched add docs dropzone to fit height

- src/app/plugins/document-explorer/components/searchbar/searchbar.component.html
- src/app/plugins/document-explorer/components/searchbar/searchbar.component.ts
- src/app/plugins/document-explorer/pages/explore/explore.component.html
- src/app/plugins/document-explorer/pages/explore/explore.component.ts
adjusted spinner
added userId and contentType to results
> moved results to explorer component from searchbar

- src/app/app.module.ts
- src/app/plugins/api-explorer/components/api-item/api-item.component.html
- src/app/plugins/api-explorer/components/api-item/api-item.component.ts
- src/app/plugins/api-explorer/pages/explore/explore.component.ts
- src/app/plugins/document-explorer/components/paging/paging.component.html
- src/app/plugins/document-explorer/components/paging/paging.component.spec.ts
- src/app/plugins/document-explorer/components/paging/paging.component.ts
- src/app/plugins/document-explorer/components/searchbar/searchbar.component.ts
- src/app/plugins/document-explorer/pages/explore/explore.component.html
- src/app/plugins/document-explorer/pages/explore/explore.component.ts
- src/app/services/api.service.ts
- src/styles.scss
fixed tag button link
updated postSearch to include query string values (paging, limit)
> added pagination

- src/app/plugins/api-explorer/components/api-item/api-item.component.html
- src/app/plugins/api-explorer/components/api-item/api-item.component.ts
- src/app/plugins/api-explorer/pages/explore/explore.component.ts
- src/app/plugins/document-explorer/pages/add/add.component.ts
- src/app/services/api.schema.ts
- src/app/services/api.service.ts
Awaiting server-side validation
> WIP: added path param (apiEx, add documents)

- package-lock.json
- package.json
- package resolutions: serialize-javascript
- package scripts preinstall: npx npm-force-resolutions
> added package params:

- src/app/plugins/document-explorer/components/searchbar/searchbar.component.html
- src/app/plugins/document-explorer/components/searchbar/searchbar.component.scss
- src/app/plugins/document-explorer/components/searchbar/searchbar.component.ts
- src/app/plugins/document-explorer/pages/tags/tags.component.html
- src/app/plugins/document-explorer/pages/tags/tags.component.ts
- src/app/plugins/document-explorer/services/search.schema.ts
- src/app/plugins/document-explorer/services/search.service.ts
- created search schema, service
> - added search params to local storage

- src/app/plugins/document-explorer/components/searchbar/searchbar.component.ts
- src/app/plugins/document-explorer/pages/explore/explore.component.html
- made today's date search default
- added tz offset to dates
- added text to make cause of no results clear
> Doc Explorer Changes

- src/app/plugins/authentication-cognito/services/cognito-authentication.service.ts
- src/app/plugins/authentication/components/change-password/change-password.component.ts
- src/app/plugins/authentication/pages/reset-password/reset-password.component.ts
> added check for valid username on reset

- src/app/plugins/authentication-cognito/services/cognito-authentication.service.ts
on newPasswordRequired (during login)
> checking for InvalidPasswordException

- src/app/plugins/authentication/components/change-password/change-password.component.html
- src/app/plugins/authentication/components/forgot-password/forgot-password.component.html
- src/app/plugins/authentication/components/login/login.component.html
- src/app/plugins/authentication/components/register/register.component.html
> added onSubmit / [enter] to auth forms

- src/app/plugins/document-explorer/pages/info/info.component.ts
> added moment and currentTimezone to doc info page

- src/app/plugins/api-explorer/components/api-item/api-item.component.ts
> fixed unexpected pasted value in date formBuilder

- src/app/modules/paging/paging.component.html
- src/app/plugins/document-explorer/components/searchbar/searchbar.component.ts
- src/app/plugins/document-explorer/pages/explore/explore.component.html
- src/app/plugins/document-explorer/pages/explore/explore.component.ts
- src/app/plugins/document-explorer/pages/info/info.component.ts
> Issue 87 return to results remembers page

- src/app/plugins/document-explorer/pages/add/add.component.html
- src/app/plugins/document-explorer/pages/add/add.component.scss
- src/assets/dist/dropzone/dropzone.css
> fixed height/scroll issue for add/dropzone

- src/app/plugins/tagging-tool/pages/screen/screen.component.ts
> fixed preset id saving

- src/app/plugins/authentication-cognito/services/cognito-authentication.service.ts
- src/app/plugins/authentication/guards/authentication-guard.service.ts
- src/app/plugins/document-explorer/components/searchbar/searchbar.component.ts
> added verify / refresh token to auth guard

- src/app/components/sidebar/sidebar.component.html
- src/app/plugins/api-explorer/components/api-item/api-item.component.ts
- src/app/plugins/api-explorer/pages/explore/explore.component.html
- src/app/plugins/api-explorer/pages/explore/explore.component.ts
- src/app/services/api.service.ts
> added formats to api explorer

- src/app/components/sidebar/sidebar.component.html
- src/app/plugins/document-explorer/components/searchbar/searchbar.component.html
- src/app/plugins/document-explorer/document-explorer-routing.module.ts
- src/app/plugins/document-explorer/pages/add/add.component.html
- src/app/plugins/document-explorer/pages/info/info.component.html
- src/app/plugins/document-explorer/pages/info/info.component.ts
- parent/child documents
- JSON content display fix
- font size changes
> tweaks to console:

- src/app/components/sidebar/sidebar.component.html
- src/app/plugins/api-explorer/components/api-item/api-item.component.html
- src/app/plugins/api-explorer/components/api-item/api-item.component.ts
- src/app/plugins/api-explorer/pages/explore/explore.component.html
- src/app/plugins/api-explorer/pages/explore/explore.component.ts
- src/app/services/api.schema.ts
- src/app/services/api.service.ts
- src/assets/config.json
- src/environments/environment.ts
> added webhooks to api explorer

- package-lock.json
- package.json
- src/app/plugins/document-explorer/pages/info/info.component.html
- src/app/plugins/document-explorer/pages/info/info.component.ts
closes #151 
Force-download not possible without adding "response-content-type" value to getDocumentUrl
> added "open file" button

- src/app/app-routing.module.ts
- src/app/components/sidebar/sidebar.component.html
- src/app/plugins/tagging-tool/pages/screen/screen.component.ts
- src/app/plugins/webhooks/pages/webhooks/webhooks.component.html
- src/app/plugins/webhooks/pages/webhooks/webhooks.component.scss
- src/app/plugins/webhooks/pages/webhooks/webhooks.component.spec.ts
- src/app/plugins/webhooks/pages/webhooks/webhooks.component.ts
- src/app/plugins/webhooks/webhooks-routing.module.ts
- src/app/plugins/webhooks/webhooks.module.ts
- src/app/services/api.service.ts
> added webhook page
